name: SCP Upload

on:
  push:
    branches:
      - master  # or your deployment branch

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "www.drsmagic.com"
          username: "guizhong"
          port: ${{ secrets.SCP_PORT || '22' }}
          key: ${{ secrets.SCP_KEY }}
          source: "./*"   
          target: "/home/guizhong/tmp"
